### ISSUE TITLE
Support bash tab completion

### ISSUE THREAD

**Issue by mithro** [xobs/wishbone-utils#3]
https://iridakos.com/tutorials/2018/03/01/bash-programmable-completion-tutorial.html

**Comment by xobs** [comment]
As of ac5a11490ab9b1bb2d2d1c0dba9cc9098cf622c5 this can now be done with `wishbone-tool -c bash`.  Might work with `$(wishbone-tool -c bash)`?  Also contains completions for zsh, fish, powershell, and elvish.

**Comment by mithro** [comment]
@xobs that is *super* awesome!
